import type { Metadata } from "next";

import "./globals.css";

import { Lexend } from "next/font/google";

const lexend = Lexend({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
